Changes After First Review
kblycaglayan/youtube-page pull request #10
Opened 2020-02-18 15:42 UTC by kblycaglayan

[Click For Live Website](https://rawcdn.githack.com/kblycaglayan/youtube-page/first-review/index.html)

**Navbar:** We set different divisions for the elements and put them in order.
**Main Video Section:** We improved the title placement and vision of the page.
**Recommended Video Section:** We put the titles on the side with the view counts and resized the thumbnails.
**Descriptive Readme:** We prepared a descriptive readme file for our project based on our TSE's past projects.
**Live Link:** We created a link for the easiness of the job.

2020-02-18 16:24 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @kblycaglayan and @MuriloRoque  :wave: 

###  Thank you for doing the changes requested by the previous reviewer :medal_sports: I see you did the changes in the previous pull request, do not open a new pull request just do the following changes, and submit for a code review using the same pull request #10 

## Page structure

**Video Size**

- [x] The video section should be bigger please fix it

- Yours

![image](https://user-images.githubusercontent.com/52209067/74753646-0abb9a80-5236-11ea-9ece-78a43df3a414.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74753714-2626a580-5236-11ea-81aa-85c74826f9f4.png)

## Generals

**Inline styling**

- [ ] please remove all inline styling from your HTML, all CSS selectors should be declared in the CSS file, I have commented your code, where I've found inline styling :arrow_double_down: 

**Code commenting**

- [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history, I have also add comments where commented code should be deleted :arrow_double_down: 

**HTML validations**

Please fix the errors found by [validator](https://validator.w3.org/)

![image](https://user-images.githubusercontent.com/52209067/74754610-7e11dc00-5237-11ea-95b1-46af366b5a3a.png)

## That's it! :raised_hands: 

## Please :pray:  do the changes :memo:  and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

Any questions? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-18 16:24 UTC, euqueme commented on index.html
> +                <iframe width="560" height="315" src="https://www.youtube.com/embed/VtM9Doxw878"
remove inline styling the width and height selectors should be put in the CSS file

2020-02-18 16:24 UTC, euqueme commented on index.html
> +                        alt="Avatar" height="50" width="50">
remove inline styling the width and height selectors should be put in the CSS file

2020-02-18 16:24 UTC, euqueme commented on index.html
> +                        alt="Subscribe" width="100" height="100">
remove inline styling the width and height selectors should be put in the CSS file

2020-02-18 16:24 UTC, euqueme commented on index.html
> +
remove empty lines from #95 to #111

2020-02-18 16:24 UTC, euqueme commented on index.html
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/VtM9Doxw878" frameborder="0"
remove inline styling the width and height selectors should be put in the CSS file

2020-02-18 16:24 UTC, euqueme commented on index.html
> +alt="Subscribe" width="100" height="100"></li>
remove inline styling the width and height selectors should be put in the CSS file

2020-02-18 16:24 UTC, euqueme commented on styles/style.css
> +} */
remove commented code from line #79 to line #148

2020-02-19 13:56 UTC, kblycaglayan commented
[**Click For Live Website**](https://raw.githack.com/kblycaglayan/youtube-page/first-review/index.html)

**Main Video Section**: We made it bigger by adjusting the position percentages.
**Clean Code**: We deleted the unnecessary comment lines.
**Styling:** We removed the inline styling from HTML file.
**Stickler:** We added stickler to check our linter errors.

Thanks for your time and efforts...

2020-02-19 14:12 UTC, rOluochKe requested changes
Hello Team!

### Good job so far, I see you have made the previously required changes by my colleagues. However you still have a few changes you need to work on.
- Rebuilt the user details section to look like the one in youtube
![details](https://user-images.githubusercontent.com/8114528/74841625-05477880-533a-11ea-9711-314c83d130e5.PNG)
- We expect something similar to this
![expected](https://user-images.githubusercontent.com/8114528/74841671-16908500-533a-11ea-9540-3f50a40ed6ec.PNG)
- Validate your html code on this [online tool](https://validator.w3.org/#validate_by_upload) and resolve the errors
![validate](https://user-images.githubusercontent.com/8114528/74841821-5b1c2080-533a-11ea-8dcd-451a1ee6e5d6.PNG)
- Add the comments section for your featured video.
- On your sidebar, work on the spacing make look like youtube one
![spacing](https://user-images.githubusercontent.com/8114528/74842118-ebf2fc00-533a-11ea-9022-e921759be098.PNG)

### Make these changes and resubmit for a new review
- For assistance, contact me on @rOluochKe
- Happy coding!

2020-02-20 10:40 UTC, MuriloRoque commented
**`[Click For Live Website](https://raw.githack.com/kblycaglayan/youtube-page/first-review/index.html)`**

**User Details Section:** We rebuilt the user details section to match the original website.
**Recommended videos section:** We adjusted the size of the images and fonts to match the original website.
**Validation:** We used the online tool you recommended us to check for errors.

Thanks for your time and efforts...

2020-02-20 13:34 UTC, davitomix commented
### **Status: Changes required.** 🛑 👀 🔍 
### Hi Team. 😄 
### Nice job so far but we have some issues to solve before move on. 💯 👍 

### Let's check the comments section:

**Here's how it looks in your project:**

![Screen Shot 2020-02-20 at 7 30 40 AM](https://user-images.githubusercontent.com/52430951/74938046-eafdb100-53b2-11ea-995d-f4dc771661a7.png)
**There's no comment section**

**Here's how it suppose to looks:** 
![Screen Shot 2020-02-20 at 7 28 50 AM](https://user-images.githubusercontent.com/52430951/74938151-11bbe780-53b3-11ea-86e5-8acad712968d.png)

### Let's check the HTML on the validator, we have one warning:

![Screen Shot 2020-02-20 at 7 33 16 AM](https://user-images.githubusercontent.com/52430951/74938280-4fb90b80-53b3-11ea-82fa-59056f0d1e93.png)


Please make the changes required and submit a new code review once you are ready! 🙏 

Happy coding! 😄 💻 

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

2020-02-21 12:41 UTC, kblycaglayan commented
[**Click For Live Website**](https://raw.githack.com/kblycaglayan/youtube-page/first-review/index.html)

**CSS issues**: Fixed.
**HTML on the validator**: Fixed
**Comments Section**: Added.

2020-02-21 12:45 UTC, lekegitrepo commented
This PR is under Review by: **_[TSE] Temitayo Adeleke_**

2020-02-21 13:14 UTC, lekegitrepo commented
## Well Done Team!!! :100: 
This project is **_Approved_** you can merge to master now.
Good luck with your next project.

### Reviewed by: _Temitayo Adeleke_

2020-02-21 13:17 UTC, lekegitrepo approved these changes
# Approved

2020-02-21 14:23 UTC, merged